export const START_EDIT_ACCOUNT_PASSWORD_ACTION_TYPE = "START_EDIT_ACCOUNT_PASSWORD_ACTION_TYPE"

export type StartEditAccountPasswordActionType = {
    type: typeof START_EDIT_ACCOUNT_PASSWORD_ACTION_TYPE,
}