export const STOP_EDIT_ACCOUNT_PASSWORD_ACTION_TYPE = "STOP_EDIT_ACCOUNT_PASSWORD_ACTION_TYPE"

export type StopEditAccountPasswordActionType = {
    type: typeof STOP_EDIT_ACCOUNT_PASSWORD_ACTION_TYPE,
}